name: "spring-boot-microservices"
services:
  catalog-service:
    image: joenjogu/bookstore-catalog-service
    container_name: catalog-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://catalog-db:5432/postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8081:8081"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f localhost:8081" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    depends_on:
      catalog-db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m

  order-service:
    image: joenjogu/bookstore-order-service
    container_name: order-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://order-db:5432/postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8082:8082"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f localhost:8082" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    depends_on:
      order-db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
